# Generated by Django 3.2.22 on 2023-10-26 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='address1',
            new_name='address',
        ),
    ]
