# Generated by Django 3.2.22 on 2023-10-24 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
    ]
