# Generated by Django 3.2.22 on 2023-10-26 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_saved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saved',
            name='listing',
        ),
        migrations.AddField(
            model_name='saved',
            name='listing',
            field=models.ManyToManyField(to='core.Listing'),
        ),
    ]
