# Generated by Django 3.2.22 on 2023-10-24 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='year',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
