# Generated by Django 3.2.22 on 2023-10-24 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_listing_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='replacement_value',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
