# Generated by Django 3.2.22 on 2023-10-26 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_listingreviews'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ListingReviews',
            new_name='ListingReview',
        ),
    ]
