# Generated by Django 3.2.22 on 2023-10-25 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_listing_replacement_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='price',
        ),
        migrations.AddField(
            model_name='listing',
            name='price_cents',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
