# Generated by Django 3.2.22 on 2023-10-27 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='lender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lender_orders', to='core.user'),
            preserve_default=False,
        ),
    ]
