# Generated by Django 3.2.22 on 2023-10-29 22:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20231027_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='lender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lender_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(default=0)),
                ('text', models.TextField(blank=True, max_length=500)),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lender_review', to=settings.AUTH_USER_MODEL)),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renter_review', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('lender', 'renter')},
            },
        ),
    ]
