# Generated by Django 3.2.22 on 2023-10-29 23:57

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20231029_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models.listing_image_file_path),
        ),
    ]
