# Generated by Django 3.2.22 on 2023-10-30 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20231030_0433'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserImages',
            new_name='UserImage',
        ),
    ]
