# Generated by Django 3.2.22 on 2023-10-31 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20231031_1912'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnavailableDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
            options={
                'unique_together': {('date',)},
            },
        ),
        migrations.AddField(
            model_name='listing',
            name='unavailable_dates',
            field=models.ManyToManyField(blank=True, to='core.UnavailableDate'),
        ),
    ]
