# Generated by Django 3.2.22 on 2023-10-31 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20231031_2158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='replacement_value',
        ),
        migrations.AddField(
            model_name='listing',
            name='replacement_value_cents',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
