# Generated by Django 3.2.22 on 2023-10-31 23:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20231031_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingreview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.ManyToManyField(to='core.Category'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='unavailable_dates',
            field=models.ManyToManyField(to='core.UnavailableDate'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='subtotal_price',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='unavailabledate',
            unique_together=set(),
        ),
    ]
